apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: https://retina-image-tagging
spec:
  template:
    spec:
      containers:
        - image: gcr.io/PROJECT/retina-image-tagging:latest
          env:
            - name: DB_HOST
              value: "34.50.82.149"
            - name: DB_NAME
              value: "retail-intelligence"
            - name: DB_USER
              value: "nodeuser"
            - name: DB_PASS
              value: "rotikeju98"
            - name: DB_PORT
              value: "5432"
            - name: GCS_BUCKET_NAME
              value: "retail-intelligence-bucket"
